import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';
import type { WeddingConfig, Guest, GuestWish, RegistryItem, ScheduleEvent, Accommodation } from '../types/wedding';
import { loadConfig, saveConfig, loadGuests, saveGuests, loadWishes, saveWishes, loadRegistry, saveRegistry, loadSchedule, saveSchedule, loadAccommodations, saveAccommodations, resetAppToFactoryDefaults } from '../utils/storage';
interface WeddingContextType { config: WeddingConfig; updateConfig:(newConfig:Partial<WeddingConfig>)=>void; guests:Guest[]; wishes:GuestWish[]; registryItems:RegistryItem[]; scheduleEvents:ScheduleEvent[]; accommodations:Accommodation[]; activeGuest:Guest|null; setActiveGuest:(guest:Guest|null)=>void; submitRsvp:(guestId:string,rsvpData:Partial<Guest>)=>boolean; registerAndRsvp:(newGuest:{name:string;email?:string;phone?:string;rsvpStatus:'attending'|'declined';partySize:number;attendingCount:number;dietaryRestrictions:string[];dietaryDetails?:string;mealSelection?:string;songRequest?:string;message?:string;companionNames?:string[]})=>Guest; addGuest:(guest:Partial<Guest>)=>Guest; updateGuest:(id:string,updates:Partial<Guest>)=>void; deleteGuest:(id:string)=>void; bulkAddGuests:(guestList:Array<Partial<Guest>>)=>void; toggleCheckIn:(id:string)=>void; addWish:(name:string,message:string)=>void; likeWish:(id:string)=>void; addRegistryItem:(item:Omit<RegistryItem,'id'>)=>void; updateRegistryItem:(id:string,item:Partial<RegistryItem>)=>void; deleteRegistryItem:(id:string)=>void; updateScheduleEvent:(index:number,event:Partial<ScheduleEvent>)=>void; updateAccommodation:(index:number,acc:Partial<Accommodation>)=>void; resetAllData:()=>void; isAdminOpen:boolean; setIsAdminOpen:(open:boolean)=>void; isAdminAuthenticated:boolean; authenticateAdmin:(pin:string)=>boolean; logoutAdmin:()=>void; searchGuest:(query:string)=>Guest|null; }
const WeddingContext=createContext<WeddingContextType|undefined>(undefined);
export const WeddingProvider:React.FC<{children:ReactNode}>=({children})=>{
 const [config,setConfigState]=useState<WeddingConfig>(loadConfig),[guests,setGuestsState]=useState<Guest[]>(loadGuests),[wishes,setWishesState]=useState<GuestWish[]>(loadWishes),[registryItems,setRegistryItemsState]=useState<RegistryItem[]>(loadRegistry),[scheduleEvents,setScheduleEventsState]=useState<ScheduleEvent[]>(loadSchedule),[accommodations,setAccommodationsState]=useState<Accommodation[]>(loadAccommodations);
 const [activeGuest,setActiveGuest]=useState<Guest|null>(null),[isAdminOpen,setIsAdminOpen]=useState(false),[isAdminAuthenticated,setIsAdminAuthenticated]=useState(()=>sessionStorage.getItem('wedding_admin_auth')==='true');
 useEffect(()=>{saveConfig(config)},[config]); useEffect(()=>{saveGuests(guests)},[guests]); useEffect(()=>{saveWishes(wishes)},[wishes]); useEffect(()=>{saveRegistry(registryItems)},[registryItems]); useEffect(()=>{saveSchedule(scheduleEvents)},[scheduleEvents]); useEffect(()=>{saveAccommodations(accommodations)},[accommodations]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search),code=p.get('code')||p.get('c'),guestParam=p.get('guest')||p.get('g');if(code){const m=guests.find(g=>g.inviteCode.toUpperCase()===code.trim().toUpperCase());if(m)setActiveGuest(m)}else if(guestParam){const m=guests.find(g=>g.name.toLowerCase().includes(guestParam.trim().toLowerCase()));if(m)setActiveGuest(m)}},[guests]);
 const updateConfig=(n:Partial<WeddingConfig>)=>setConfigState(p=>({...p,...n}));
 const addGuest=(d:Partial<Guest>):Guest=>{const id=`g-${Date.now()}`,initials=(d.name||'G').split(' ').map(n=>n[0]).join('').toUpperCase().slice(0,2),inviteCode=`CA-${initials}${Math.floor(1000+Math.random()*9000)}`,g:Guest={id,name:d.name||'Guest',email:d.email||'',phone:d.phone||'',inviteCode,rsvpStatus:(d.rsvpStatus as any)||'pending',partySize:d.partySize||2,attendingCount:d.attendingCount||0,dietaryRestrictions:d.dietaryRestrictions||[],dietaryDetails:d.dietaryDetails||'',mealSelection:d.mealSelection||'',songRequest:d.songRequest||'',message:d.message||'',tableNumber:d.tableNumber||'Unassigned',isPlusOneAllowed:d.isPlusOneAllowed??true,companionNames:d.companionNames||[],checkedIn:false};setGuestsState(p=>[g,...p]);return g};
 const updateGuest=(id:string,u:Partial<Guest>)=>{setGuestsState(p=>p.map(g=>g.id===id?{...g,...u}:g));if(activeGuest?.id===id)setActiveGuest(p=>p?{...p,...u}:null)};
 const deleteGuest=(id:string)=>{setGuestsState(p=>p.filter(g=>g.id!==id));if(activeGuest?.id===id)setActiveGuest(null)};
 const bulkAddGuests=(list:Array<Partial<Guest>>)=>{const c=list.map((g,i)=>({id:`g-${Date.now()}-${i}`,name:g.name||'Guest',email:g.email||'',phone:g.phone||'',inviteCode:`CA-${(g.name||'G').split(' ').map(n=>n[0]).join('').toUpperCase().slice(0,2)}${Math.floor(1000+Math.random()*9000)}`,rsvpStatus:'pending' as const,partySize:g.partySize||2,attendingCount:0,dietaryRestrictions:[],tableNumber:g.tableNumber||'Unassigned',isPlusOneAllowed:g.isPlusOneAllowed??true,companionNames:[]}));setGuestsState(p=>[...c,...p])};
 const toggleCheckIn=(id:string)=>setGuestsState(p=>p.map(g=>g.id===id?{...g,checkedIn:!g.checkedIn}:g));
 const addWish=(name:string,message:string)=>setWishesState(p=>[{id:`w-${Date.now()}`,name,message,date:new Date().toISOString().slice(0,10),likes:1},...p]);
 const likeWish=(id:string)=>setWishesState(p=>p.map(w=>w.id===id?{...w,likes:(w.likes||0)+1}:w));
 const submitRsvp=(id:string,u:Partial<Guest>)=>{const t=guests.find(g=>g.id===id);if(!t)return false;const updated={...t,...u,respondedAt:new Date().toISOString()};setGuestsState(p=>p.map(g=>g.id===id?updated:g));setActiveGuest(updated);if(u.message&&u.message.trim().length>3)addWish(t.name,u.message.trim());return true};
 const registerAndRsvp=(d:any)=>{const c=addGuest(d),f={...c,...d,respondedAt:new Date().toISOString()};updateGuest(c.id,f);setActiveGuest(f);if(d.message&&d.message.trim().length>3)addWish(d.name,d.message.trim());return f};
 const addRegistryItem=(item:Omit<RegistryItem,'id'>)=>setRegistryItemsState(p=>[...p,{...item,id:`reg-${Date.now()}`}]);
 const updateRegistryItem=(id:string,u:Partial<RegistryItem>)=>setRegistryItemsState(p=>p.map(r=>r.id===id?{...r,...u}:r)); const deleteRegistryItem=(id:string)=>setRegistryItemsState(p=>p.filter(r=>r.id!==id));
 const updateScheduleEvent=(i:number,e:Partial<ScheduleEvent>)=>setScheduleEventsState(p=>{const n=[...p];if(n[i])n[i]={...n[i],...e};return n}); const updateAccommodation=(i:number,a:Partial<Accommodation>)=>setAccommodationsState(p=>{const n=[...p];if(n[i])n[i]={...n[i],...a};return n});
 const resetAllData=()=>resetAppToFactoryDefaults(); const authenticateAdmin=(pin:string)=>{if(pin===config.adminPin){setIsAdminAuthenticated(true);sessionStorage.setItem('wedding_admin_auth','true');return true}return false}; const logoutAdmin=()=>{setIsAdminAuthenticated(false);sessionStorage.removeItem('wedding_admin_auth')};
 const searchGuest=(q:string)=>{if(!q?.trim())return null;const c=q.trim().toLowerCase();return guests.find(g=>g.inviteCode.toLowerCase()===c)||guests.find(g=>g.name.toLowerCase()===c)||guests.find(g=>g.name.toLowerCase().includes(c))||guests.find(g=>(g.email&&g.email.toLowerCase()===c)||(g.phone&&g.phone.includes(c)))||null};
 return <WeddingContext.Provider value={{config,updateConfig,guests,wishes,registryItems,scheduleEvents,accommodations,activeGuest,setActiveGuest,submitRsvp,registerAndRsvp,addGuest,updateGuest,deleteGuest,bulkAddGuests,toggleCheckIn,addWish,likeWish,addRegistryItem,updateRegistryItem,deleteRegistryItem,updateScheduleEvent,updateAccommodation,resetAllData,isAdminOpen,setIsAdminOpen,isAdminAuthenticated,authenticateAdmin,logoutAdmin,searchGuest}}>{children}</WeddingContext.Provider>};
export const useWedding=()=>{const c=useContext(WeddingContext);if(!c)throw new Error('useWedding must be used within a WeddingProvider');return c};